# This image inherits from the Production version and installs the required
# libraries in order to run the tests.
#
# This will allow then to push the production image (and not this image) which
# will not have all the stuff for running the tests.
#
FROM zedtux/brewformulas.org:latest
MAINTAINER zedtux, zedtux@zedroot.org

USER root
RUN apt-get update && apt-get install -y make gcc g++

USER brewformulas
RUN bundle config --delete without && \
    bundle install --jobs 8
