#!/usr/bin/env ruby

path = "#{File.dirname(__FILE__)}"
path << '/../vendor/{gems,plugins}/cucumber*/bin/cucumber'
vendored_cucumber_bin = Dir[path].first
if vendored_cucumber_bin
  load File.expand_path(vendored_cucumber_bin)
else
  require 'rubygems' unless ENV['NO_RUBYGEMS']
  require 'cucumber'
  load Cucumber::BINARY
end
