Feature: Fetch formula description
  In order to understand what is the purpose of a formula
  As a robot
  I want to fetch it from the formula homepage
  So that it can be shown on brewformulas.org

  Scenario Outline: Fetch formula description from homepage
    Given following Homebrew formula exists:
      | filename | <filename> |
      | name     | <name>     |
      | homepage | <homepage> |
    When the background task to fetch formula description runs
    Then the formula <name> should have the following description:
    """
    <description>
    """
  Examples:
    | filename      | name        | homepage                                                         | description                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
    | a2ps          | A2ps        | http://www.gnu.org/software/a2ps/                                | GNU a2ps is an Any to PostScript filter. Of course it processes plain text files, but also pretty prints quite a few popular languages.                                                                                                                                                                                                                                                                                                                                                                                                                                                     |
    | abcl          | Abcl        | http://abcl.org/                                                 | Armed Bear Common Lisp (ABCL) is a full implementation of the Common Lisp language featuring both an interpreter and a compiler, running in the JVM.                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    | abook         | Abook       | http://abook.sourceforge.net/                                    | Abook is a text-based addressbook program designed to use with mutt mail client. Abook runs on Linux, FreeBSD and some other UNIXes.                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    | ack           | Ack         | http://beyondgrep.com/                                           | ack 2.10 is a tool like grep, optimized for programmers Designed for programmers with large heterogeneous trees of source code, ack is written purely in portable Perl 5 and takes advantage of the power of Perl's regular expressions.                                                                                                                                                                                                                                                                                                                                                    |
    | acpica        | ACPICA      | https://www.acpica.org/                                          | The ACPI Component Architecture (ACPICA) project provides an operating system (OS)-independent reference implementation of the Advanced Configuration and Power Interface Specification (ACPI). It can be easily adapted to execute under any host OS. The ACPICA code is meant to be directly integrated into the host OS as a kernel-resident subsystem. Hosting the ACPICA subsystem requires no changes to the core ACPICA code. Instead, a small OS-specific interface layer is written specifically for each host OS in order to interface the ACPICA code to the native OS services. |
    | activemq      | Activemq    | http://activemq.apache.org/                                      | Apache ActiveMQ ™ is the most popular and powerful open source messaging and Integration Patterns server.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   |
    | bib-tool      | BibTool     | http://www.gerd-neugebauer.de/software/TeX/BibTool/index.en.html | No description available                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
    | adobe-air-sdk | AdobeAirSdk | http://adobe.com/products/air/sdk                                | The Adobe AIR SDK provides the tools necessary to build and deploy Adobe AIR applications.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  |
    | afuse         | Afuse       | https://github.com/pcarrier/afuse/                               | An automounter implemented with FUSE                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        |
    | aircrack-ng   | AircrackNg  | http://aircrack-ng.org/                                          | Aircrack-ng is an 802.11 WEP and WPA-PSK keys cracking program that can recover keys once enough data packets have been captured. It implements the standard FMS attack along with some optimizations like KoreK attacks, as well as the all-new PTW attack, thus making the attack much faster compared to other WEP cracking tools.                                                                                                                                                                                                                                                       |
    | zopfli        | Zopfli      | https://code.google.com/p/zopfli/                                | Zopfli Compression Algorithm is a new zlib (gzip, deflate) compatible compressor. This compressor takes more time (~100x slower), but compresses around 5% better than zlib and better than any other zlib-compatible compressor we have found.                                                                                                                                                                                                                                                                                                                                             |
    | zsh           | Zsh         | http://www.zsh.org/                                              | Zsh is a shell designed for interactive use, although it is also a powerful scripting language.                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             |

  Scenario: Try to fetch the description from an URL responding with a 404 error
    Given the Libgadu formula with homepage "http://toxygen.net/libgadu/" exists
    When the background task to fetch formula description runs
    Then the formula Libgadu should have the following description:
    """
    No description available
    """
